pipeline {
    agent any
    environment {
        M2_HOME='/opt/apache-maven-3.9.9'
        PATH="${M2_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkup 1') {
            sh 'pwd'
            sh 'ls -l'
        }
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage('Checkup 2') {
            sh 'pwd'
            sh 'ls -l'
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
