pipeline {
    agent any
    environment {
        M2_HOME='/opt/apache-maven-3.9.9'
        PATH="${M2_HOME}/bin:${PATH}"
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage('Prepare Environment') {
            steps {
                // Verify Maven installation
                sh 'mvn -version'
            }
        }
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'ls -l'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
